### ISSUE TITLE
Default subject if not defined for @endpoint

### ISSUE THREAD

**Issue by petrarca** [charbonats/nats-micro#2]
If not defined for the @endpoint, would  be great if defaulted (or resolved) to {name of the service}.{name}. Name is either specified in the endpoint or defaulted to name of the function.

```
@service(name = "some-service")
@endpoint
async some_endpoint( ...):
```

endpoint subject will be some-service.some_endpoint

If service name and subject shall be different, this should be specifiable on the @service. Like @service(endpoint_subject="...", ...)

**Comment by charbonnierg** [comment]
The name of services in micro is not a subject. So we should never treat a service name as a subject.

I'm not in favor of adding `endpoint_subject` argument either because it does not exist in the spec.

A  `group`  can be used to add a prefix to several endpoints. However I dont think they make sense when using decorators. So for now, I'd say either add a prefix to each endpoint subject manually, or use a [prefix](https://github.com/charbonats/nats-micro/blob/14a2c4f87cbf2c878b991bf165b9a169b94858c5/src/nats_contrib/micro/sdk/decorators.py#L137) when mounting the service.

What are your arguments in favor of this ?  Why would an additional change in this library make it easier compared to:

```python
MY_PREFIX = "something"

@micro.sdk.service(...)
class Srv:
    @micro.sdk.endpoint(subject=f"{MY_PREFIX}.foo")
    async def foo(self, request: micro.Request):
        ...
```

**Comment by petrarca** [comment]
Agree on your arguments. Let's stay close to the spec.
