### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by petrarca** [charbonats/nats-micro#4]
I tried to pass a configuration into the updated micro.sdk.run, but failed with different approaches. Can you please provide an example (e.g. list of servers). I tried `ConnectOpts`, but failed. `setup` works without any problems (including registering new services).

```
    options = ??

    micro.sdk.run(
            setup = setup,
            trap_signals=True,
            *options,
            )

```

**Comment by charbonnierg** [comment]
You should be able to use:

EDIT: This example is wrong

```python
   from nats_contrib.connect_opts import option
   from nats_contrib import micro

   micro.sdk.run(
            setup = setup,
            trap_signals=True,
            option.WithServer("nats://localhost:4222"),
            # Add any other options as required
            )
```

This test file can give you an idea on how to use each option: https://github.com/charbonats/nats-connect-opts/blob/main/tests/test_connect_opts.py

**Comment by petrarca** [comment]
have tried this, but get still error "Positional argument cannot appear after keyword arguments" in `micro.sdk.run()`

**Comment by charbonnierg** [comment]
Ah yes, that's True... So `setup` must be used as a positional argument and `trap_signal` must be the last argument.

```python
from nats_contrib.connect_opts import option
from nats_contrib import micro

micro.sdk.run(
    setup,
    option.WithServer("nats://localhost:4222"),
    # Add any other options as required
    # ...
    trap_signals=True,
)

**Comment by charbonnierg** [comment]
I pushed a commit which requires `setup` argument  to be positional: https://github.com/charbonats/nats-micro/commit/6138551be9e111f319535a3f8ca3e1938745ce2b

**Comment by charbonnierg** [comment]
Do you have any suggestion in mind regarding a more user friendly API to configure NATS ?

I don't really want to support each option as a keyword argument for two reasons:
- Some options are almost always used in pair (like the max reconnect attempt and the reconnect delay)
- It's painful to write a function signature with 30+ arguments with proper type annotations

So I really like the option pattern, where any function responsible for connecting to NATS has a simple pattern - it accepts an unlimited number of connect topions: `func(opts *ConnectOption)` .

The problem here is that we also want additional arguments such as `setup` and `trap_signals`. I thought it would be OK to require `setup` to be positional, and to leave `trap_signals` as a keyword argument only.

**Comment by petrarca** [comment]
It works now. I think that is fine for now. I think this is a good compromise to have setup as positional and trap_signals as kwarg. I can alway create a NATS client if I need more control.
